---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: diverdane/nginxdualstack:1.0.0
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-ipv4
  labels:
    app: nginx
spec:
  ipFamilyPolicy: SingleStack
  ipFamilies:
  - IPv4
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-ipv6
  labels:
    app: nginx
spec:
  ipFamilyPolicy: SingleStack
  ipFamilies:
  - IPv6
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80


# === External Loadbalancer ===
# Note: IPv4 works with Neutron LBaaSv2 but IPv6 needs Octavia
#       --> Check your cloud.conf in kubeone.yaml

# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: nginx-ipv4-external
#   labels:
#     app: nginx
# spec:
#   type: LoadBalancer
#   ipFamilyPolicy: SingleStack
#   ipFamilies:
#   - IPv4
#   selector:
#     app: nginx
#   ports:
#     - protocol: TCP
#       port: 80

# NOTE: External IPv6 LoadBalancer requires Octavia (neutron doesn't support that)
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: nginx-ipv6-external
#   annotations:
#     service.beta.kubernetes.io/openstack-internal-load-balancer: "true"
#     loadbalancer.openstack.org/subnet-id: "72a9c428-d56a-4367-91eb-ba23ed85ba9a"
#   labels:
#     app: nginx
# spec:
#   type: LoadBalancer
#   ipFamilyPolicy: SingleStack
#   ipFamilies:
#   - IPv6
#   selector:
#     app: nginx
#   ports:
#     - protocol: TCP
#       port: 80
